/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeTest */

#ifndef _Included_NativeTest
#define _Included_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeTest
 * Method:    some
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_NativeTest_some
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
